-- MySQL Script generated by MySQL Workbench
-- 09/02/18 16:16:08
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbodbc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbodbc` ;
CREATE SCHEMA IF NOT EXISTS `dbodbc` DEFAULT CHARACTER SET utf8 ;
USE `dbodbc` ;

-- -----------------------------------------------------
-- Table `dbodbc`.`tipologin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbodbc`.`tipologin` ;

CREATE TABLE IF NOT EXISTS `dbodbc`.`tipologin` (
  `idTipoLogin` INT(11) NOT NULL AUTO_INCREMENT,
  `tipoLogin` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idTipoLogin`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbodbc`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbodbc`.`usuario` ;

CREATE TABLE IF NOT EXISTS `dbodbc`.`usuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbodbc`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbodbc`.`login` ;

CREATE TABLE IF NOT EXISTS `dbodbc`.`login` (
  `idLogin` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `idTipoLogin` INT(11) NOT NULL,
  INDEX `fk_Login_TipoLogin_idx` (`idTipoLogin` ASC),
  INDEX `fk_login_usuario1_idx` (`idLogin` ASC),
  PRIMARY KEY (`idLogin`),
  CONSTRAINT `fk_Login_TipoLogin`
    FOREIGN KEY (`idTipoLogin`)
    REFERENCES `dbodbc`.`tipologin` (`idTipoLogin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_login_usuario1`
    FOREIGN KEY (`idLogin`)
    REFERENCES `dbodbc`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `dbodbc`.`tipologin`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbodbc`;
INSERT INTO `dbodbc`.`tipologin` (`idTipoLogin`, `tipoLogin`) VALUES (1, 'Socio');
INSERT INTO `dbodbc`.`tipologin` (`idTipoLogin`, `tipoLogin`) VALUES (2, 'Administrador');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbodbc`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbodbc`;
INSERT INTO `dbodbc`.`usuario` (`idUsuario`, `nombre`, `apellido`, `direccion`, `telefono`, `email`) VALUES (1, 'Kevin', 'Fiorentino', 'UNLa', 1131768187, 'kevin@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `dbodbc`.`login`
-- -----------------------------------------------------
START TRANSACTION;
USE `dbodbc`;
INSERT INTO `dbodbc`.`login` (`idLogin`, `user`, `pass`, `idTipoLogin`) VALUES (1, 'socio', '1111', 1);

COMMIT;
